"use client";

import { useEffect, useState } from "react";
import {
  EDGE_TYPE_LABELS,
  NODE_STATUSES,
  NODE_TYPES,
  NODE_TYPE_REGISTRY,
  NODE_STATUS_META,
  type EdgeType,
  type NodeType,
  type NodeStatus,
} from "@branchwork/domain";
import { useStore } from "../state/store";

const SHORTCUTS: [string, string][] = [
  ["Tab", "New child under selection"],
  ["Shift+Enter", "New sibling"],
  ["Enter", "Edit selected card"],
  ["Esc", "Finish editing / clear selection"],
  ["Delete", "Delete selected card or edge"],
  ["Ctrl/⌘+Z", "Undo"],
  ["Ctrl/⌘+L", "Lay out selected branch"],
  ["Ctrl/⌘+E", "Export project JSON"],
  ["Double-click edge label", "Select edge, change its type here →"],
];

export function InspectorPanel() {
  const nodes = useStore((s) => s.nodes);
  const edges = useStore((s) => s.edges);
  const selectedNodeIds = useStore((s) => s.selectedNodeIds);
  const selectedEdgeId = useStore((s) => s.selectedEdgeId);
  const updateNode = useStore((s) => s.updateNode);
  const setEdgeType = useStore((s) => s.setEdgeType);
  const deleteEdge = useStore((s) => s.deleteEdge);

  const node =
    selectedNodeIds.length === 1 ? nodes[selectedNodeIds[0] as string] : undefined;
  const edge = selectedEdgeId ? edges[selectedEdgeId] : undefined;

  if (edge) {
    return (
      <aside className="bw-inspector">
        <h3>Connection</h3>
        <label className="bw-field">
          Type
          <select
            value={edge.type}
            onChange={(e) => setEdgeType(edge.id, e.target.value as EdgeType)}
          >
            {(Object.keys(EDGE_TYPE_LABELS) as EdgeType[]).map((t) => (
              <option key={t} value={t}>
                {EDGE_TYPE_LABELS[t]}
              </option>
            ))}
          </select>
        </label>
        <p className="bw-muted">
          {nodes[edge.sourceNodeId]?.title || edge.sourceNodeId} →{" "}
          {nodes[edge.targetNodeId]?.title || edge.targetNodeId}
        </p>
        <button className="btn bw-danger-btn" onClick={() => deleteEdge(edge.id)}>
          Delete connection
        </button>
      </aside>
    );
  }

  if (node) {
    return (
      <aside className="bw-inspector">
        <h3>{NODE_TYPE_REGISTRY[node.type].label}</h3>
        <p className="bw-muted mono">{node.id}</p>
        <label className="bw-field">
          Card type
          <select
            value={node.type}
            onChange={(e) => updateNode(node.id, { type: e.target.value as NodeType })}
          >
            {NODE_TYPES.map((t) => (
              <option key={t} value={t}>
                {NODE_TYPE_REGISTRY[t].label}
              </option>
            ))}
          </select>
        </label>
        <label className="bw-field">
          Status
          <select
            value={node.status}
            onChange={(e) => updateNode(node.id, { status: e.target.value as NodeStatus })}
          >
            {NODE_STATUSES.map((s) => (
              <option key={s} value={s}>
                {NODE_STATUS_META[s].label}
              </option>
            ))}
          </select>
        </label>
        <TagEditor key={node.id} nodeId={node.id} tags={node.tags} />
        <p className="bw-hint">
          Created {new Date(node.createdAt).toLocaleString()}
          <br />
          Updated {new Date(node.updatedAt).toLocaleTimeString()}
        </p>
        {node.modelRunId && (
          <p className="bw-provenance">
            ✦ Generated by model run <code>{node.modelRunId}</code>. Human edits are preserved.
          </p>
        )}
      </aside>
    );
  }

  return (
    <aside className="bw-inspector">
      <h3>Branchwork</h3>
      <p className="bw-muted">
        Select a card to edit its type, status, and tags. Nothing here is decoration — types drive
        context assembly, citations, and outlines.
      </p>
      <h4>Keyboard</h4>
      <dl className="bw-shortcuts">
        {SHORTCUTS.map(([keys, description]) => (
          <div key={keys} className="bw-shortcut-row">
            <dt>
              <kbd>{keys}</kbd>
            </dt>
            <dd>{description}</dd>
          </div>
        ))}
      </dl>
    </aside>
  );
}

function TagEditor({
  nodeId,
  tags,
}: {
  nodeId: string;
  tags: string[];
}) {
  const updateNode = useStore((s) => s.updateNode);
  const [draft, setDraft] = useState(tags.join(", "));

  useEffect(() => {
    setDraft(tags.join(", "));
  }, [tags.join(",")]); // eslint-disable-line react-hooks/exhaustive-deps

  const commit = () => {
    const next = draft
      .split(",")
      .map((t) => t.trim())
      .filter(Boolean);
    if (next.join(",") !== tags.join(",")) updateNode(nodeId, { tags: next });
  };

  return (
    <label className="bw-field">
      Tags (comma separated)
      <input value={draft} onChange={(e) => setDraft(e.target.value)} onBlur={commit} />
    </label>
  );
}
